### PR TITLE
Support mod subdirectories

### PR DESCRIPTION
**Pull request by ItsKaa**
This adds support for reading mods in (nested) sub-directories and modifies the displayed name in the UI (limited to the `Configure Mods` and `Manage Mods` pages) with that of the directory tree, excluding the last folder that is often the mod id.

I prefer this a bit more since I am often downloading and updating mods manually, and not every mod author uses a naming convention that makes sense to me.

## Notes
* This does change the base ConfigService, so applications will also listen to changes in the sub-directories. I don't think this is a big deal really but the adjusted watchers could be moved if needed.
* Updating the new mod properties right after reading the configurations.
  * I had to override `AddItem` for this because otherwise it would mess up in the `Manage Mods` page when a mod got modified.
* I also fixed the bug you mentioned, #306.
  * (I would have liked to use `DistinctBy` but that's .net 6 and this particular library also builds on .net 5)

## Preview
image
image

The directory tree inside my `Mods` folder:
```
├───reloaded.sharedlib.hooks
├───reloaded.universal.redirector
├───Reloaded.Utils.Server
├───Something
│   └───reloaded.universal.something
└───Test
    └───Another Folder
        ├───reloaded.universal.monitor
        └───Yet Another Folder
            └───TestModControlParams
```

Moving a folder deletes all mods containing that folder, same for adding a folder with multiple mods inside it, and again works when renaming a folder. I have also not found any issues editing mods so far.

(By the way, editing a mod and closing the form always results in a save, I would have expected it to cancel. Though it did actually help me in testing.)

Let me know what you think, maybe you could do a bit of testing yourself since I only recently started using R2. No need to rush though.

### CODE REVIEW

**Comment by Sewer56** [comment]
Been a busy work week, so sorry for the delay, here's some thoughts.

## Unrestricting Search Depth

This will require a patch which says 'don't look in subdirectories if you found a config file here'.
Otherwise we will search over all of the user's mod files, which may considerably slow things down as large Reloaded setups can have 100+k files.

## Deduplicating Configs by ID

There's a small caveat here.
When looking for configs, the launcher does a depth first search.
The order of the files is an implementation detail of the filesystem, but for NTFS, it's alphabetical.

So if you have (`Mods` Folder)
- `AModGroup/ModA/ModConfig.json`
- `ModA/ModConfig.json`

It will use the `ModA` inside `AModGroup` first (alphabetical). 
If the user then renames `AModGroup` on disk to `ZModGroup`.
Then it'll use `ModA` inside main `Mods` folder.

There's a risk that user can rename this, and not launch the launcher, then end up with an outdated mod. It's fairly improbable, and probably not likely enough to be very significant, but it technically exists. 

As long as modders are warned to not distribute multiple mods under 1 download, things will probably be ok.

## Misc Notes

- LINQ should be avoided in hot paths, as it has overhead. 
- Using directory separators '/' to denote subfolders will probably be friendlier to the user. Though this is subjective, so I'm happy to hear thoughts.

## Folder Watchers

I'll debug how this works at runtime and give an update in next post.

**Comment by ItsKaa** [comment]
Thanks for your comments, and honestly, 2 days response is rather fast, I did say no rush!

> Unrestricting Search Depth

The search depth restriction is a good suggestion. Didn't think too much about the file count and I suppose nobody really should nest mods inside a folder that already contains a ModConfig file anyway.


> Deduplicating Configs by ID

This may be a bit out of scope, but I wonder, would it not be a good idea to implement a duplicate mod check in the launcher then? Then at least the user could be notified of the problem, and it could even be triggered when new mods are detected in the watchers (as long as it doesn't spam message boxes every time a mod is added/moved).

Maybe even a conflict resolver but that would probably take a bit more time to implement. (because I sometimes found myself having to manually edit the json files because the mod author released optional files that didn't have a unique mod id).

Then again as you said before, since R2 is in maintenance mode I'm not sure how much time should be spent on this bit. We could change the code to handle such a situation but it could also be mentioned in the documentation.


> Using directory separators '/' to denote subfolders will probably be friendlier to the user. Though this is subjective, so I'm happy to hear thoughts.

Frankly, I don't mind changing the notation, this is like you said subjective and I bet other people will have different opinions, a setting is an option but I'm not sure if it really matters that much either. I can always change it to dashes in my own branch if I feel like it.


I'll have some time in the weekend.

**Comment by Sewer56** [comment]
I've cleaned up this PR, to make sure performance characteristics are up to scratch with expectation.
They're not ideal, ideally you'd have a full tree of nodes to do something like this, but chances are, it's good enough up to 2000 mods for the time being.

**Comment by ItsKaa** [comment]
Removing the directory separators causes a problem where if you have two directories with a very similar name, say:
* `ModA`
* `ModA Extra`

And if you then delete the whole `ModA` folder, the mods in both directories will be removed since the check will see if `Mods\ModA` contains within any mod path which will be the case for `Mods\ModA Extra`, adding the directory separators handles such a scenario. I think it would be better to revert the commit 1895275 and 2dc822e.

Other than that, the changes look good!

**Comment by Sewer56** [comment]
> Removing the directory separators causes a problem where if you have two directories with a very similar name, say:
> 
>     * `ModA`
> 
>     * `ModA Extra`
> 
> 
> And if you then delete the whole `ModA` folder, the mods in both directories will be removed since the check will see if `Mods\ModA` contains within any mod path which will be the case for `Mods\ModA Extra`, adding the directory separators handles such a scenario.

Aah, you're right. I was thinking this whole time I might have missed an edge case, that's it. I'll fix this up when I get to my PC.

**Comment by Sewer56** [comment]
Should be good now 👍

**Pull request merged**
